baseURL = "https://sunagimon.github.io"
languageCode = "en-us"
title = "Takuto Ukawa | 宇川 拓人 Portfolio"
theme = "sunagimon-theme"

[taxonomies]

[markup.goldmark.renderer]
  unsafe = true

# Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/#about"
        weight  = 2
    [[menu.nav]]
        name    = "Works"
        url     = "/#works-jump"
        weight  = 3
    [[menu.nav]]
        name    = "Contact"
        url     = "/#call-to-action"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
  
# Params
[params]
    home = "Home"
    logo = "images/home/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "宇川拓人(Takuto Ukawa)のポートフォリオです. 関わった制作物などを紹介してます."
    author = "sunagimon"
    keywords = "宇川拓人, Takuto Ukawa, 東京大学, sunagimon"
    # Google Analitycs
    googleAnalitycsID = "UA-132429975-1"

    # Banner
    [params.banner]
        enable  = true
        bgImage = "images/home/back.jpg"
        icImage = "images/home/icon.jpg"
        heading = "Takuto Ukawa"
        description = "Master degree Student of the University of Tokyo, Human-Computer Interaction creator, Smoked food lover"
        [[params.banner.flipText]]
            title   = "GRADUATE STUDENT"
        [[params.banner.flipText]]
            title   = "CREATOR"
        [[params.banner.flipText]]
            title   = "SMOKED FOOD LOVER"

    # About
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Takuto Ukawa (宇川 拓人) is currently a Master's student in the <a href= https://www.ogawa-lab.org/ target=”_blank”>Takefumi Ogawa Laboratory</a> at The University of Tokyo in Japan. <br> He is studying Emerging Design and Informatics in the graduate school, after finished Bachelor's degree in Electrical Engineering. <br> His current research area is Human-Computer Interaction and Interaction Design. <br> <br> And he is Smoked food Lover, usually spend his time smoking meats and fish. "
        image   = "images/about/me.png"

    # Works
    [params.portfolio]
        enable  = true
        title   = "works"
    
    # Contact
    [params.cta]
        enable  = true
        title = "contact"
        content   = "Please let me know if you need anything."
    

