baseURL = "https://sunagimon.github.io"
languageCode = "en-us"
title = "Takuto Ukawa | 宇川 拓人 Portfolio"
theme = "sunagimon-theme"

[taxonomies]

[markup.goldmark.renderer]
  unsafe = true

# Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/#about"
        weight  = 2
    [[menu.nav]]
        name    = "Works"
        url     = "/#works-jump"
        weight  = 3
    [[menu.nav]]
        name    = "Contact"
        url     = "/#call-to-action"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
  
# Params
[params]
    home = "Home"
    logo = "images/home/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "宇川拓人(Takuto Ukawa)のポートフォリオです. 関わった制作物などを紹介してます."
    author = "sunagimon"
    keywords = "宇川拓人, Takuto Ukawa, 東京大学, Design, Art"
    # Google Analitycs
    googleAnalitycsID = "UA-132429975-1"

    # Banner
    [params.banner]
        enable  = true
        bgImage = "images/home/back.jpg"
        icImage = "images/home/icon.jpg"
        heading = "Takuto Ukawa"
        description = ""
        [[params.banner.flipText]]
            title   = "CREATOR"
        [[params.banner.flipText]]
            title   = "ENGINEER"
        [[params.banner.flipText]]
            title   = "SMOKED FOOD LOVER"

    # About
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        title_  = "　"
        content = "宇川拓人 1994年 千葉県生まれ.  <br> 2020年 東京大学大学院 学際情報学府 先端表現情報学コース修了.  <br> 学生時代は小川剛史研究室にて Human Computer Interaction , Interaction Design 分野の研究を行う. <br> 現在, 電機メーカーで映像技術の開発をするかたわら, クリエーター活動をしている.  <br> 制作物はインタラクティブコンテンツ, ゲーム, メディアデザインやアートなど. <br> 主な出展先としては「墨田児童会館」(2019.5), 「Eureka」(2019.3), 「東京大学制作展」(2018.11)などがある.  <br>  <br> 趣味は燻製.  <br> しばしば肉を加工している.  <br> "
        econtent = "Takuto Ukawa. Born in 1994, in Chiba, Japan. <br> He got his master's degree from The University of Tokyo in  Emerging Design and Informatics Course in 2020. <br> His research was in the field of Human-Computer Interaction and Interaction Design at Takefumi Ogawa Lab. <br> Currently, he is an engineer doing video technology development at an electronics manufacturer and also personally active as a creator.<br> Some of his past projects include interactive content, games, and media design hand art. <br> He participated in some major exhibitions: Sumida Children's Center (2019.5), Eureka (March 2019), iii Exhibition (2018.11). <br> <br> And he is a smoked food lover, usually spends his time smoking meat and fish. <br> "

    # Works
    [params.portfolio]
        enable  = true
        title   = "works"
    
    # Contact
    [params.cta]
        enable  = true
        title = "contact"
        content   = "Please let me know if you need anything."
    

